services:
  - type: web
    name: cltv-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard.app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8080
